version: '2'
services:
  db:
    image: postgres:9.4.5
    volumes:
      - web-postgres:/var/lib/postgresql/data
  web-test:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - BUNDLE_PATH=/bundle
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - web-redis:/var/lib/redis/data
volumes:
  web-postgres:
  web-redis:
